/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Home Design 3D (https://sketchfab.com/homedesign3d)
license: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
source: https://sketchfab.com/3d-models/city-apatment-c1a719c1b34a4bbaa2f7a781eeb9b082
title: City Apatment
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/apartment.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['20201114-182611-mez']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['20201114-182619-mez']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['20210501-94924-mesz']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['20210501-95126-mesz']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['20210501-95826-mesz']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['20210505-151311-mesz']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['20210505-151313-mesz']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['20210505-151318-mesz']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['20210505-151410-mesz']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['20210505-151439-mesz']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['20210505-15152-mesz']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['20210508-10107-mesz']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['20210811-162755-mesz']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['20210829-195940-mesz']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['20211021-16101-mesz']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['20211021-16112-mesz']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['20211021-161143-mesz_Wall_Entity_Material']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['20211021-1683-mesz_Room_Entity_Material']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['20211021-16835-mesz']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['20211021-16842-mesz']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['20211021-16850-mesz']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials['20211021-1686-mesz']} />
        <mesh geometry={nodes.Object_24.geometry} material={materials['20211021-1686-mesz_Room_Entity_Material']} />
        <mesh geometry={nodes.Object_25.geometry} material={materials['20211021-16911-mesz']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['20211021-16930-mesz']} />
        <mesh geometry={nodes.Object_27.geometry} material={materials['20211021-16940-mesz']} />
        <mesh geometry={nodes.Object_28.geometry} material={materials['20211021-16947-mesz']} />
        <mesh geometry={nodes.Object_29.geometry} material={materials['20211021-16953-mesz']} />
        <mesh geometry={nodes.Object_30.geometry} material={materials['20211028-132258-wesz_Room_Entity_Material']} />
        <mesh geometry={nodes.Object_31.geometry} material={materials['20211101-132924-mez']} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.bamboo___bamboo_feuille} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.bamboo___bamboo_gazon} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.bamboo___bamboo_tronc} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.beige_006_Wall_Entity_Material} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.blanc_001_Wall_Entity_Material} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.bleu_010_Wall_Entity_Material} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.bureau_012___mat_bois044sg} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.enduit_004_Room_Entity_Material} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.enduit_004_Wall_Entity_Material} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.fake_mat_115_113_113_255} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.fake_mat_115_113_113_255} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.fake_mat_122_141_154_255} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.fake_mat_140_139_132_255} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.fake_mat_156_45_55_255} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.fake_mat_174_127_42_255} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.fake_mat_178_209_224_255} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.fake_mat_191_174_181_255} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.fake_mat_191_174_181_255} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.fake_mat_192_188_180_255} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.fake_mat_192_188_180_255} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.fake_mat_209_205_98_255} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.fake_mat_232_229_221_255} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.fake_mat_232_229_221_255} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.fake_mat_236_113_5_255} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.fake_mat_248_249_247_255} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.fake_mat_255_255_255_32} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.fake_mat_28_28_28_255} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.fake_mat_3_3_3_255} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.fake_mat_3_3_3_255} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.fake_mat_62_64_67_255} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.fake_mat_62_64_67_255} />
        <mesh geometry={nodes.Object_63.geometry} material={materials.fake_mat_70_100_46_255} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.fake_mat_70_100_46_255} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.indu_canape_002_4p_noir_2___pied_canape_indu_002} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.kitchen_vintage_style_base_cabinet_oven_002___m_plaque} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.kitchen_vintage_style_base_cabinet_oven_002___m_poignet} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.kitchen_vintage_style_base_cabinet_oven_002___m_wood} />
        <mesh geometry={nodes.Object_69.geometry} material={materials.kitchen_vintage_style_dishwasher_000___m_panneau_machine} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.kitchen_vintage_style_dishwasher_000___m_wood_surface} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.lit_arche___lit_arche_cercle} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.lit_arche___lit_arche_gris} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.lit_arche___lit_arche_gris_fonce} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.marbre_006_ovcol4c4c4ccolpic12contpic09} />
        <mesh geometry={nodes.Object_75.geometry} material={materials.meuble_lavabo_007___meuble_lavabo_007alphabois} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.meuble_scandinave_ww___phong2} />
        <mesh geometry={nodes.Object_77.geometry} material={materials.meuble_scandinave_ww___phong95} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.pack_004_cuisine_001_tableau___photo} />
        <mesh geometry={nodes.Object_79.geometry} material={materials.pack_004_salon_001_plante___nopaint_feuilles} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.pack_004_salon_001_plante___terreau} />
        <mesh geometry={nodes.Object_81.geometry} material={materials.pack_005_chambre_001_table___feuille_decoupe002} />
        <mesh geometry={nodes.Object_82.geometry} material={materials.pack_005_chambre_001_table___nopaint_dessin} />
        <mesh geometry={nodes.Object_83.geometry} material={materials.pack_005_chambre_001_table___poignees} />
        <mesh geometry={nodes.Object_84.geometry} material={materials.parquet_022_Room_Entity_Material} />
        <mesh geometry={nodes.Object_85.geometry} material={materials.reading_table_bis___cahier_a_spiralesg} />
        <mesh geometry={nodes.Object_86.geometry} material={materials.reading_table_bis___net_book1} />
        <mesh geometry={nodes.Object_87.geometry} material={materials.reading_table_bis___standard_3} />
        <mesh geometry={nodes.Object_88.geometry} material={materials.refrigerateur_006____refrigerateur_006_refrigerateur_006_refrigerateur_006glacon} />
        <mesh geometry={nodes.Object_89.geometry} material={materials.refrigerateur_006____refrigerateur_006_refrigerateur_006_refrigerateur_006porte} />
        <mesh geometry={nodes.Object_90.geometry} material={materials.scan_accessoirebain_001___cuir_jaune} />
        <mesh geometry={nodes.Object_91.geometry} material={materials.scan_accessoirebain_001___metal_chromer} />
        <mesh geometry={nodes.Object_92.geometry} material={materials.scan_accessoirebain_001___mirroir} />
        <mesh geometry={nodes.Object_93.geometry} material={materials.scan_luminaire_002_rouger___bois_003} />
        <mesh geometry={nodes.Object_94.geometry} material={materials.scan_luminaire_002_rouger___phong21sg3} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.set_001_meuble_tv___ceramic_vase_1} />
        <mesh geometry={nodes.Object_96.geometry} material={materials.set_001_meuble_tv___plastic_ecran} />
        <mesh geometry={nodes.Object_97.geometry} material={materials.tableau_noir_001___ardoise} />
        <mesh geometry={nodes.Object_98.geometry} material={materials.tableau_noir_001___grille} />
        <mesh geometry={nodes.Object_99.geometry} material={materials.tex_tapis_scan_motif_turquoise_014_ovcol4c4c4ccolpic12contpic09} />
        <mesh geometry={nodes.Object_100.geometry} material={materials.texture_eau_piscine} />
        <mesh geometry={nodes.Object_101.geometry} material={materials.vint_buffet_001___bois_002} />
        <mesh geometry={nodes.Object_102.geometry} material={materials.vint_buffet_001___metal_orcre} />
        <mesh geometry={nodes.Object_103.geometry} material={materials.wall_backLeft_Wall_Entity_Material} />
        <mesh geometry={nodes.Object_104.geometry} material={materials.wall_backRight_Wall_Entity_Material} />
        <mesh geometry={nodes.Object_105.geometry} material={materials.wall_frontLeft_Wall_Entity_Material} />
        <mesh geometry={nodes.Object_106.geometry} material={materials.wall_frontRight_Wall_Entity_Material} />
        <mesh geometry={nodes.Object_107.geometry} material={materials.wall_left_Wall_Entity_Material} />
        <mesh geometry={nodes.Object_108.geometry} material={materials.wall_right_Wall_Entity_Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/apartment.glb')
